FROM python:3
# install pipenv
# RUN apt update && \
#     apt install -y pipenv
# install poetry
# RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
WORKDIR /var/www/html
EXPOSE 80
